### ISSUE TITLE
Should answer questions about freeCodeCamp on Quora be included?

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/contribute#1]
I've seen that there are a lot of questions on Quora (918 at the time) about freeCodeCamp. Should a link to the freeCodeCamp topic (https://www.quora.com/topic/freeCodeCamp-1) on Quora be included? Is that another significant way to contribute?

**Comment by raisedadead** [comment]
Great, question. But I think we should be limiting the areas to where we can have an oversight on the community (for the sake of enforcing guidelines).

YouTube, Forum, Code and Chat have moderators who manage it.

Quora is rather more of a Open resource, just like you would say wikipedia. And think beyond the scope?

**Comment by nsuchy** [comment]
As @raisedadead mentioned we have no control over content on Quora. This issue should be closed.
