### ISSUE TITLE
Contributing guidelines landing page redirects to incorrect link

### ISSUE THREAD

**Issue by bhusal-rj** [freeCodeCamp/contribute#117]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
This bug is mentioned in the PR #54865 in the freeCodeCamp Repo.
On the [Contributing Guidelines landing page](https://contribute.freecodecamp.org/#/), the fourth link down which reads “Contribute to our open-source codebase on GitHub” currently redirects users to the [Learning Platform](https://contribute.freecodecamp.org/#/index?id=learning-platform) subsection of the contributing guidelines. This is misleading as the language and icon used both imply that it will direct users to the GitHub repository.

**Affected Page**
https://contribute.freecodecamp.org/#/

**To Reproduce**
1. Click on "Issues" tab on the FreeCodeCamp GitHub repository
2. Click on the "contributing guide" link at the top of the page
3. Click on the link https://contribute.freecodecamp.org/ which takes you to the contributing guide landing page
4. Arrive at the affected link which is the fourth one down that reads "Contribute to our open-source codebase on GitHub"

**Expected behavior**
It must redirect to the github repo of the freeCodeCamp

**Screenshots**
![image](https://github.com/freeCodeCamp/contribute/assets/33444884/0e82f373-dbf9-4ab7-a37c-9e60a5e99455)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 120.0.6099.224

**Comment by bhusal-rj** [comment]
I have raised the PR #118 for this issue

**Comment by majestic-owl448** [comment]
Note that the PR is not going to change the live site, which is still the legacy one, only the new version that is not yet live

**Comment by raisedadead** [comment]
Thanks for this issue Rajesh. As we see it, we think the quick intro about the platform is useful - I see where you are coming from though. Going ahead and closing this for now.
