### ISSUE TITLE
CSS Styles are not working in production builds

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#127]
For some reason CSS Styles are not working in production builds, I suspect this is a bug with Starlight. 

To reproduce:

1. Run `npm run develop`. Visit http://localhost:4321
2. Kill the development server.
3. Run `npm run build` to create a production build.
4. Run `npm start` to run the production server. Visit http://localhost:3000

**Comment by raisedadead** [comment]
This may have to do with the nightmode button behavior.

**Comment by a2937** [comment]
Can you elaborate on what you mean by "doesn't work"? I mean ,yes, it starts on light mode on start but everything seems the same between the develop and start modes.

**Comment by raisedadead** [comment]
Sorry about the late reply, I am trying this on an incognito window in macOS on a chromimum based browser. The device is set to dark mode by default. You will notice once you click the night mode icon, the CSS works correctly going forward.

https://github.com/freeCodeCamp/contribute/assets/1884376/5d69be0e-f988-4be6-a501-fe30c67c6c42

**Comment by a2937** [comment]
That's certainly odd. Thanks for pointing it out. 

![Screenshot](https://github.com/freeCodeCamp/contribute/assets/9373245/4715ef66-0ddf-413d-8140-ea6e36ffbaac)

This is what I usually see. I'm on Windows and usually using light mode. I'm going to try my best to replicate this issue locally and fix it. However this issue kind of reminds me of when I had a bad Google Chrome extension added to my account.

**Comment by gikf** [comment]
I can reproduce it in incognito, or after clearing cookies from `contribute.freecodecamp.org` (or both). Applies to light and dark preferred color scheme.

https://github.com/freeCodeCamp/contribute/assets/60067306/3548a199-abdd-44fa-8092-e59309954cea

- - -

~~Firefox doesn't seem to be affected in this way.~~
Firefox also does that on first load, with no cookies.

**Comment by a2937** [comment]
I think I know why this is happening. You see when the page first loads without cookies, neither the dark class nor light class are immediately applied.

**Comment by a2937** [comment]
I'm going to try to follow this recipe to fix this. 
https://astro-tips.dev/recipes/dark-mode/
