### ISSUE TITLE
Broken images with relative src

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/contribute#136]
**Describe the bug**
There's few images with `src` attribute starting with dot. This makes them link to incorrect location.

For example:
`https://contribute.freecodecamp.org/how-to-translate-files/images/crowdin/translated-screenshot.png`
instead of:
`https://contribute.freecodecamp.org/images/crowdin/translated-screenshot.png`

Affected files:
https://github.com/search?q=repo%3AfreeCodeCamp%2Fcontribute%20img%20src%3D%22.&type=code

Removing the dot should deal with the problem.

**Screenshots**
![image](https://github.com/freeCodeCamp/contribute/assets/60067306/29091e2c-81bf-4a20-b628-398cb046554c)

**Comment by a2937** [comment]
![image](https://github.com/freeCodeCamp/contribute/assets/9373245/9a620c41-aaa4-464f-b96b-d3557cc22ac2)


In my defense, it was working fine locally. There was no way for me to know that it wouldn't work in deployment. Regardless I will get on this.

**Comment by raisedadead** [comment]
This is not documented (very well yet), but you should be able to launch a production like setup:

```
npm run build
npm start
```

I have mentioned these commands in the project readme for now.

**Comment by gikf** [comment]
> In my defense, it was working fine locally. There was no way for me to know that it wouldn't work in deployment. Regardless I will get on this.

To be honest, I'm not sure there's any need for the defense 🙂
