### ISSUE TITLE
Hamburger icon should replace with close icon if menu opens up

### ISSUE THREAD

**Issue by kapilG0** [freeCodeCamp/contribute#187]
### Describe the Issue

Hamburger icon needs to be replaced with close icon if menu opens up

### Affected Page

https://contribute.freecodecamp.org/faq/

### Steps to Reproduce

[Screenshot_20240624_221959](https://github.com/freeCodeCamp/freeCodeCamp/assets/59639410/e9a6d5d4-13c0-445a-9484-4090c82c27b5)

### Expected behavior

[Screenshot_20240624_221959](https://github.com/freeCodeCamp/freeCodeCamp/assets/59639410/9d89096d-3a00-4136-b8a4-9b152f47fccf)

### Screenshots

[Screenshot_20240624_221959](https://github.com/freeCodeCamp/freeCodeCamp/assets/59639410/fe1f9f1e-287b-484c-8d88-4879006c4370)

### System

- Device: android 
- Browser: chrome

**Comment by kapilG0** [comment]
Hello @alinmigea please assign this issue to me under gssoc 24

**Comment by majestic-owl448** [comment]
Issues are not assigned, if you are interested in contributing please check the issues with the help wanted label @kapilG0

**Comment by bbsmooth** [comment]
I don't think it is essential that the icon visually change to a close button, but it won't hurt anything. The accessible name on the button, currently defined as "Menu" with the aria-label attribute should NOT change however. 

Also, I'm noticing that while this button does have the aria-expanded attribute set to false when the menu is not visible, it does not change to true when the menu is visible. This is a WCAG failure that needs to be fixed. I am noticing that the custom starlight-menu-button element wrapping the button also has an aria-expanded attribute and that is toggling true and false as the button is clicked. This is unnecessary on this element. It's the actual button element that needs to toggle the aria-expanded value.
