### ISSUE TITLE
Logo in header gets resized to very small size

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/contribute#198]
**Describe the bug**
When resizing page, the logo in header can get really small. This happens when there's still lots of space to keep it bigger.

**Expected behavior**
Logo should be kept bigger when there's still space for it.

**Screenshots**
- Just before header is changed to mobile view:
![image](https://github.com/freeCodeCamp/contribute/assets/60067306/a89bdc7b-bf42-4724-98c5-fa034b9ccf5b)

- Logo in mobile view at around 400px width:
![image](https://github.com/freeCodeCamp/contribute/assets/60067306/dc07848e-659e-4aa8-8cfb-f560b9f9c982)

- The _normal_ size of logo:
![image](https://github.com/freeCodeCamp/contribute/assets/60067306/730c4c32-5df3-49d4-8b7f-cbfb4f1ede44)

**Comment by michaelhiiva** [comment]
What is the size we are looking to have with this logo?
