### ISSUE TITLE
Spike on a SSG & CMS for building the site

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#2]
Look at a few static site generators and consider them for the project. Quick note that we want to stick to the JAMStack ecosystem, mainly because most contributors to fCC are most comfortable with JavaScript.

Please leave comments, we will deliberate for the next few days.
```[tasklist]
### CMS
- [ ] Tina - https://tina.io
- [ ] DecapCMS - https://decapcms.org/
```

```[tasklist]
### Web Frameworks
- [ ] NextJS
- [ ] Astro
- [ ] Remix
- [ ] 11ty
- [x] ~~Gatsby~~ : Not an ideal candidate based on the main platform experience
```

**Comment by raisedadead** [comment]
## CMS

1. https://tina.io - Tina is Git-based but I believe depends on "Tina Cloud".
2. https://decapcms.org - Decap CMS (Formerly Netlify CMS) can be self-managed??


## Website Framework

### NextJS

I think this will be a great option because of the powerful ecosystem of NextJS, helping us build a full-blown platform starting with the docs website. The caveat is having to maintain a server – which is OK by me.

### Astro

I have heard very good things about it including minimal JS in the browser. Need to investigate more on this tool.

### 11ty

11ty is a trusted SSG we have known to love from its use in building the main news platform.

**Comment by SaintPeter** [comment]
I look a look at some of the JAMStack "Git Based" CMSes, including TinaCMS and DecapCMS. It looks like we can enable a workflow of sorts which allows WYSIWYG editing via the web, with a commit to a side branch, then "publish" via PR. I like the low overhead editing.

Take a look at this:  
https://decapcms.org/docs/open-authoring/

One thing that is no entirely clear from my perusing of the docs is how permissions are handled. We clearly need to prevent drive-by vandalism, but still reduce the overhead to making a correction or contribution.

**Comment by raisedadead** [comment]
Yes - I liked it as well. Its much closer to the ideal workflow we want. 

I was doing some research and found this post: https://www.njfamirm.ir/en/blog/self-hosting-decap-cms - where they use a custom GitHub OAuth2 wrapper for auth.

From my initial brainstorming, I think "Open Authoring" with GitHub Backend + [this GitHub OAuth from the blog](https://github.com/njfamirm/decap-cms-github-backend) will suffice our needs.

Now coming to prevent vandalism, we an fork that OAuth wrapper to add additional checks on it including, querying GitHub for checking recency of the user's account creation date and things like that, or checking if they are blocked by us, etc.

**Comment by raisedadead** [comment]
Closing, we have settled on Astro and Decap
