### ISSUE TITLE
Landing Page Stylistic changes

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#20]
The current landing page is quite stock and could use some stylistic changes including better CTAs. I would love for the @freeCodeCamp/moderators to take a second and drop your ideas here.

For the current version of the site (in development) visit: `https://beta.contribute.freecodecamp.org` (using code tags to avoid any unwanted indexing and traffic.

**Comment by lynxlynxlynx** [comment]
The get-started button gets in the way — it's only appropriate for code contributors, while the intro makes it sound more are targeted. For anyone else, the blocks below are more relevant and could potentially get discouraged if they visited the button link. That applies at least to translators, but it'd be useful to think about who you want to attract, so you can cater to all.

I'd base the page on what they can contribute (code, translation, docs, being nice, whatever) or what they are ("I'm a translator", "I'm a tester", "I'm a mediator" ...), with sections for each group with their own details, CTAs and links.

**Comment by a2937** [comment]
Is it just me or is our logo a little small on my phone? Secondly those last two links aren't taking me anywhere. 


![Screenshot_20240506_094400_Firefox](https://github.com/freeCodeCamp/contribute/assets/9373245/6ac12f9c-ad3b-4ed9-bdcf-a6ad6c97d826)
