### ISSUE TITLE
[BUG] No hover effect on the "Get Started" Button

### ISSUE THREAD

**Issue by chinmaykeni9422** [freeCodeCamp/contribute#204]
### Describe the Issue

There is no hover effect present on the "Get started" button which makes user experience less interactive and dull

### Affected Page

https://contribute.freecodecamp.org/intro/

### Steps to Reproduce

1. Go to intro page
2. locate the "Get started" button
3. Hover on it you will notice the issue

### Expected behavior

There should be an hover effect when we hover on it something like making background color bit more light when we hover on that button

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/137027001/34f6f153-d088-4205-aa08-9a3e1e043538)

### System

- Device: Laptop [DESKTOP-86Q9HQH]
- OS: Windows 11
- Browser: Chrome
- Version: 126.0.6478.127

### Additional context

Hey!!  this my first bug report i hope it's well described and organized

**Comment by TMack88** [comment]
I would like to work on this current issue

**Comment by saksha914** [comment]
would like to work on this issue

**Comment by SaintPeter** [comment]
@TMack88 @saksha914 
We don't assign issues, be take the first acceptable PR. You're welcome to come up with a fix and then reference this issue number in your PR. (IE: `closes: #204`), it will automatically close this issue when merged.

When the PR is reviewed you'll also get any feedback from the reviews and a chance to make corrections.

**Comment by ewaforman** [comment]
I also confirm, that there is no effect after hovering over button “Get started”.

**Affected Page**

https://contribute.freecodecamp.org/intro/

**System**

OS: Windows 11
Browser: Chrome Version: 127.0.6533.99
Firefox Version 129.0 
Edge Version 127.0.2651.86

**Comment by Neema-Joju** [comment]
Hi,
Does anyone know which page is actually affected? Like which page in github or pages! I am new here so, I am just trying to figure things out.

**Comment by a2937** [comment]
What color was it supposed to be?

**Comment by TomLincoln066** [comment]
is there a color code that's required?

**Comment by a2937** [comment]
I was trying to remember what colors were used on the style guide.
