### ISSUE TITLE
Add close or a exit button on a searching window

### ISSUE THREAD

**Issue by Nayanj041** [freeCodeCamp/contribute#377]
### Is your feature request related to a problem? Please describe.

when i clicked on a searching tab but when i want to go back i don't fine any close and exit option on a tab

### Describe the solution you'd like

simply add  (**X**) to close that search window

### Describe alternatives you've considered

there is an alternative to make it attractive by adding backward arrow  (**<-**) 

### Additional context

![Screenshot 2024-10-01 230737](https://github.com/user-attachments/assets/d06eb4c0-d4ac-4180-a5c0-40a7f7b2f511)

**Comment by BlazeBoy22** [comment]
i want to work on this feature addition , please assign me this issue

**Comment by Nayanj041** [comment]
Go ahead bro

**Comment by majestic-owl448** [comment]
@BlazeBoy22 @Nayanj041 this issue is not open for contribution, please look at issues with the 'help wanted' label

**Comment by yassenezed** [comment]
Hey can i work on this please assign me

**Comment by raisedadead** [comment]
This feature comes straight from the upstream starlight repository, so fixes/suggestions need to be implemented there. That said I found hitting escape or clicking outside the search area to be quite intuitive and standard practice.

Closing for now.
