### ISSUE TITLE
Broken Link in "Setup a dev environment for freeCodeCamp" Page

### ISSUE THREAD

**Issue by MacMacky** [freeCodeCamp/contribute#385]
__Describe the issue__
The __what we recommend__ link is wrong, upon checking the value is https://contribute.freecodecamp.org/how-to-setup-freecodecamp-locally/?id=how-to-prepare-your-local-machine, I think it should be https://contribute.freecodecamp.org/how-to-setup-freecodecamp-locally#how-to-prepare-your-local-machine

![Image](https://github.com/user-attachments/assets/b574997f-9734-4dc8-97d8-d2ef83ee0469)
![Image](https://github.com/user-attachments/assets/97c92d1e-32e6-4dd4-9942-3585bacf1dbe)

__Expected Behavior__
it should go to this part of the page
![Image](https://github.com/user-attachments/assets/e01b34ee-8d31-44a5-b2be-e30ab3cec157)

Happy to make a PR 🙂 for this

**Comment by gikf** [comment]
There's few other places where link should be updated:

https://github.com/freeCodeCamp/contribute/blob/a5c0cda81ab19865eb35673ee1ee00f932681f25/src/content/docs/how-to-setup-freecodecamp-locally.mdx?plain=1#L210

https://github.com/freeCodeCamp/contribute/blob/a5c0cda81ab19865eb35673ee1ee00f932681f25/src/content/docs/reply-templates.mdx?plain=1#L40

https://github.com/freeCodeCamp/contribute/blob/a5c0cda81ab19865eb35673ee1ee00f932681f25/src/content/docs/reply-templates.mdx?plain=1#L152
