### ISSUE TITLE
Spike on Localization and Crowdin Setup

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#4]

**Comment by a2937** [comment]
It's very lovely and nice that Starlight supports internalization out of the box. If we want a similar setup to the legacy version we could add something similar to this in `astro.config.mjs`. 


```
  locales: {
    root: {
      label: 'English',
      lang: 'en'
    },
  }
```

**Comment by raisedadead** [comment]
Oh - that's amazing! Are you suggesting we could start using the content we have? 

@naomi-lgbt quick sanity check with you here, what happens if we uploaded the current (`main`) version of the docs. Are we able to get a good enough match? Or should we wait for the rewrites of the articles?

**Comment by naomi-lgbt** [comment]
I'd have to update the directory settings, but yeah any docs that weren't substantially changed should pull pretty well from translation memory.

**Comment by a2937** [comment]
I would update the heads of the doc files first and check for any additional issues. I'll happily set up a PR and see what I can do.  

Edit: Just remembered about the links too. I have to update them to not use the file extension and then there's the banners that will also need to be taken care of.
