### ISSUE TITLE
Excessive Email Notifications

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/contribute#42]
I'm getting a crapton of emails from this specific repo. Can we reduce the pings to the entire moderator list?

**Comment by raisedadead** [comment]
Thanks for the feedback and sorry about the noise. Allow us time to think about this. 

Please know that we do want the mods to be the [`CODEOWNERS`](https://github.com/freeCodeCamp/contribute/blob/main/.github/CODEOWNERS) for the repository. It is crucial for the content and code that goes into this project should be reviewed by this team who shepherd the community.

Unfortunately GitHub doesn't yet allow for very granular control for teams. It has some controls. I have just enabled it:

<img width="1071" alt="image" src="https://github.com/freeCodeCamp/contribute/assets/1884376/9afbb285-dd03-4ddb-aa42-b6f27f6bd357">

The above does rely on the human creating the PR to request review to a person on the team first (while moving from draft to ready state).

Meanwhile I recommend a few options that can reduce the noise:

- You should be able to update your accounts watch settings for a given repo.
  <details>
   <summary>Details</summary>
	
   <img width="490" alt="image" src="https://github.com/freeCodeCamp/contribute/assets/1884376/500df3e4-cca5-4561-8487-9955f4c0029f">
	
  </details>

- You should also be able to able to route emails in https://github.com/settings/notifications/custom_routing

  <details>
   <summary>Details</summary>

   <img width="1039" alt="image" src="https://github.com/freeCodeCamp/contribute/assets/1884376/6429494d-e786-4d1e-a1d6-28cd89002ad3">

  </details>

  This does mean adding another email address to your account. For example a `no-op` email address like `mygmailid+no-op@gmail.com`, and you could then add filter on that in your email app.


I understand this may not be the ideal response you are looking for, but we will continue ponder over the problem trying to find balance.

**Comment by raisedadead** [comment]
I have temporarily switched the ownership in 7420498 - will revert it when the project becomes more stable.
