### ISSUE TITLE
Remap old URLs

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#79]
We need to add a handler for URL scheme between Docsify and Astro:

```diff
- /#/how-to-work-on-localized-client-webapp?id=file-structure
+ /how-to-work-on-localized-client-webapp/#file-structure
```

- Handle the `#/` by removing it.
- Handle the `?id=` query param swapping it with a `/#`

**Comment by a2937** [comment]
I had an idea on how to do this. I have a local prototype in progress. 

https://docs.astro.build/en/guides/endpoints/#redirects
